# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75085869b4bb4d2bf027a2693e2d40e1368204b65591759636aec85b191328e316966a3d17752d50b38788eb4dd846106e7f12bc1082b22386bdae1c564f7c6d

test:
  secret_key_base: 8b8a69909c543d97a11722f7a1bb66b8f0eb24b3a5c9ca87290e353f9b276e9d78c06e5fd986cb84ca88cf32da4ab4a505ee4260775fa12182573452c462e946

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
